version: "3"

services:
  mysql-development:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: matcha
      MYSQL_USER: flo
      MYSQL_PASSWORD: password
    ports:
      - 33080:3306
    volumes:
      - ./Matcha.sql:/docker-entrypoint-initdb.d/Matcha.sql
  adminer:
    image: adminer
    ports:
      - 8081:8080
